# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t9Oy4xOjeKU0Hao6181vmGw3PkTXQDgP
"""

def preprocess(df, seq, p=3, Label=True):

    # Step 1: Filtering the file to remove empty, N, or multimutations.
    # Step 2: Adding downstream and upstream nucleotides.
    # Step 3: Normalizing position values.

    dic = {'A':0, 'T':1, 'C':2, 'G':3}

    if Label:
        df = df[['Chromosome', 'Start_Position', 'Alt' , 'Ref','label']]
    else:
        df = df[['Chromosome', 'Start_Position', 'Alt' , 'Ref']]

    for i in range(1,p+1):
        df[str(i)+' position'] = 0
        df[str(-1*i)+' position'] = 0

    Filtered = []
    df['Ref'].replace(['-'], ['None'], inplace=True)
    df['Alt'].replace(['-'], ['None'], inplace=True)

    index = 0

    for i in range(len(seq)):

      if seq[i][0]=='>':
        index+=1
      elif seq[i][0]!='N':

        if len(df['Ref'][index-1])==1 and len(df['Alt'][index-1])==1:
            for j in range(1,p+1):
              df[str(j)+' position'][index-1] = dic[seq[i][10+j]]
              df[str(-1*j)+' position'][index-1] = dic[seq[i][10-j]]
            Filtered.append(index-1)

    df = df.iloc[Filtered]
    df = df.reset_index(drop=True)
    df['Ref'].replace(['A','T','C','G'], [0,1,2,3], inplace=True)
    df['Alt'].replace(['A','T','C','G'], [0,1,2,3], inplace=True)
    if Label:
        df['label'].replace(['tissue','CH'], [0,1], inplace=True)

    df.loc[df['Chromosome']=='X', ['Chromosome']] = 23
    df.loc[df['Chromosome']=='Y', ['Chromosome']] = 24

    # Normalizing positions with mean and standard deviation estimated at 100,000,000 and 120,000,000, respectively.
    df['Start_Position'] = (df['Start_Position']-100000000)/120000000
    return df

def initial_process(unlabel_vcf, unlabel_seq):

    # Converting chromosome (chr) to numerical value.
    # Filtering chromosomes 1 to 23, as well as X and Y.

    unlabeled= unlabel_vcf[['chr','pos','ref','alt']]
    dic= {}
    for i in range(22):
        dic['chr'+str(i+1)] = i+1
    dic['chrX'] = 23
    dic['chrY'] = 24
    chromosomes = list(dic.keys())

    unlabeled = unlabeled.loc[unlabeled['chr'].isin(chromosomes)]
    unlabeled['chr'].replace(chromosomes, list(dic.values()), inplace=True)

    unlabels = unlabeled.rename(columns= {'chr':'Chromosome' , 'pos': 'Start_Position' , 'ref':'Ref' , 'alt' : 'Alt'})

    unlabels = preprocess(unlabels , unlabel_seq , Label=False)
    return unlabels